"""create users table

Revision ID: 9d0c65b844cd
Revises: 
Create Date: 2026-08-14 08:44:02.836792

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9d0c65b844cd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

user_role = postgresql.ENUM("USER", "ADMIN", name="user_role", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role.create(op.get_bind(), checkfirst=True)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', user_role, server_default='USER', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('profile_image_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(full_name)) > 0', name='ck_users_full_name_not_blank'),
    sa.CheckConstraint('length(btrim(password_hash)) > 0', name='ck_users_password_hash_not_blank'),
    sa.CheckConstraint('length(email) > 0 AND email = lower(btrim(email))', name='ck_users_email_normalized'),
    sa.CheckConstraint('profile_image_key IS NULL OR length(btrim(profile_image_key)) > 0', name='ck_users_profile_image_key_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_users_email', table_name='users')
    op.drop_table('users')
    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
